# Generated by Django 5.1.4 on 2026-07-18 14:23

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_on_trial',
            field=models.BooleanField(default=True, help_text='Uncheck once the business has converted (paid).'),
        ),
        migrations.AddField(
            model_name='client',
            name='trial_ends_at',
            field=models.DateTimeField(default=clients.models.default_trial_end),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Manual on/off switch for this business.'),
        ),
    ]
